#!/usr/bin/env ruby
module LyjiasMimeTypesReference
  TYPES = {"audio/aac"=>
  {:extension=>".aac",
   :description=>"AAC audio file",
   :mime_type=>"audio/aac"},
 "application/x-abiword"=>
  {:extension=>".abw",
   :description=>"AbiWord document",
   :mime_type=>"application/x-abiword"},
 "application/octet-stream"=>
  {:extension=>".bin",
   :description=>"Any kind of binary data",
   :mime_type=>"application/octet-stream"},
 "video/x-msvideo"=>
  {:extension=>".avi",
   :description=>"AVI: Audio Video Interleave",
   :mime_type=>"video/x-msvideo"},
 "application/vnd.amazon.ebook"=>
  {:extension=>".azw",
   :description=>"Amazon Kindle eBook format",
   :mime_type=>"application/vnd.amazon.ebook"},
 "application/x-bzip"=>
  {:extension=>".bz",
   :description=>"BZip archive",
   :mime_type=>"application/x-bzip"},
 "application/x-bzip2"=>
  {:extension=>".bz2",
   :description=>"BZip2 archive",
   :mime_type=>"application/x-bzip2"},
 "application/x-csh"=>
  {:extension=>".csh",
   :description=>"C-Shell script",
   :mime_type=>"application/x-csh"},
 "text/css"=>
  {:extension=>".css",
   :description=>"Cascading Style Sheets (CSS)",
   :mime_type=>"text/css"},
 "text/csv"=>
  {:extension=>".csv",
   :description=>"Comma-separated values (CSV)",
   :mime_type=>"text/csv"},
 "application/vnd.ms-fontobject"=>
  {:extension=>".eot",
   :description=>"MS Embedded OpenType fonts",
   :mime_type=>"application/vnd.ms-fontobject"},
 "application/epub+zip"=>
  {:extension=>".epub",
   :description=>"Electronic publication (EPUB)",
   :mime_type=>"application/epub+zip"},
 "image/gif"=>
  {:extension=>".gif",
   :description=>"Graphics Interchange Format (GIF)",
   :mime_type=>"image/gif"},
 "text/html"=>
  {:extension=>".html",
   :description=>"HyperText Markup Language (HTML)",
   :mime_type=>"text/html"},
 "image/x-icon"=>
  {:extension=>".ico",
   :description=>"Icon format",
   :mime_type=>"image/x-icon"},
 "text/calendar"=>
  {:extension=>".ics",
   :description=>"iCalendar format",
   :mime_type=>"text/calendar"},
 "application/java-archive"=>
  {:extension=>".jar",
   :description=>"Java Archive (JAR)",
   :mime_type=>"application/java-archive"},
 "image/jpeg"=>
  {:extension=>".jpg", :description=>"JPEG images", :mime_type=>"image/jpeg"},
 "application/javascript"=>
  {:extension=>".js",
   :description=>"JavaScript (ECMAScript)",
   :mime_type=>"application/javascript"},
 "application/json"=>
  {:extension=>".json",
   :description=>"JSON format",
   :mime_type=>"application/json"},
 "audio/midi"=>
  {:extension=>".mid",
   :description=>"Musical Instrument Digital Interface (MIDI)",
   :mime_type=>"audio/midi"},
 "video/mpeg"=>
  {:extension=>".mpeg", :description=>"MPEG Video", :mime_type=>"video/mpeg"},
 "application/vnd.apple.installer+xml"=>
  {:extension=>".mpkg",
   :description=>"Apple Installer Package",
   :mime_type=>"application/vnd.apple.installer+xml"},
 "application/vnd.oasis.opendocument.presentation"=>
  {:extension=>".odp",
   :description=>"OpenDocument presentation document",
   :mime_type=>"application/vnd.oasis.opendocument.presentation"},
 "application/vnd.oasis.opendocument.spreadsheet"=>
  {:extension=>".ods",
   :description=>"OpenDocument spreadsheet document",
   :mime_type=>"application/vnd.oasis.opendocument.spreadsheet"},
 "application/vnd.oasis.opendocument.text"=>
  {:extension=>".odt",
   :description=>"OpenDocument text document",
   :mime_type=>"application/vnd.oasis.opendocument.text"},
 "audio/ogg"=>
  {:extension=>".oga", :description=>"OGG audio", :mime_type=>"audio/ogg"},
 "video/ogg"=>
  {:extension=>".ogv", :description=>"OGG video", :mime_type=>"video/ogg"},
 "application/ogg"=>
  {:extension=>".ogx", :description=>"OGG", :mime_type=>"application/ogg"},
 "font/otf"=>
  {:extension=>".otf", :description=>"OpenType font", :mime_type=>"font/otf"},
 "image/png"=>
  {:extension=>".png",
   :description=>"Portable Network Graphics",
   :mime_type=>"image/png"},
 "application/pdf"=>
  {:extension=>".pdf",
   :description=>"Adobe Portable Document Format (PDF)",
   :mime_type=>"application/pdf"},
 "application/vnd.ms-powerpoint"=>
  {:extension=>".ppt",
   :description=>"Microsoft PowerPoint",
   :mime_type=>"application/vnd.ms-powerpoint"},
 "application/x-rar-compressed"=>
  {:extension=>".rar",
   :description=>"RAR archive",
   :mime_type=>"application/x-rar-compressed"},
 "application/rtf"=>
  {:extension=>".rtf",
   :description=>"Rich Text Format (RTF)",
   :mime_type=>"application/rtf"},
 "application/x-sh"=>
  {:extension=>".sh",
   :description=>"Bourne shell script",
   :mime_type=>"application/x-sh"},
 "image/svg+xml"=>
  {:extension=>".svg",
   :description=>"Scalable Vector Graphics (SVG)",
   :mime_type=>"image/svg+xml"},
 "application/x-shockwave-flash"=>
  {:extension=>".swf",
   :description=>"Small web format (SWF) or Adobe Flash document",
   :mime_type=>"application/x-shockwave-flash"},
 "application/x-tar"=>
  {:extension=>".tar",
   :description=>"Tape Archive (TAR)",
   :mime_type=>"application/x-tar"},
 "image/tiff"=>
  {:extension=>".tif",
   :description=>"Tagged Image File Format (TIFF)",
   :mime_type=>"image/tiff"},
 "application/typescript"=>
  {:extension=>".ts",
   :description=>"Typescript file",
   :mime_type=>"application/typescript"},
 "font/ttf"=>
  {:extension=>".ttf", :description=>"TrueType Font", :mime_type=>"font/ttf"},
 "application/vnd.visio"=>
  {:extension=>".vsd",
   :description=>"Microsoft Visio",
   :mime_type=>"application/vnd.visio"},
 "audio/x-wav"=>
  {:extension=>".wav",
   :description=>"Waveform Audio Format",
   :mime_type=>"audio/x-wav"},
 "audio/webm"=>
  {:extension=>".weba", :description=>"WEBM audio", :mime_type=>"audio/webm"},
 "video/webm"=>
  {:extension=>".webm", :description=>"WEBM video", :mime_type=>"video/webm"},
 "image/webp"=>
  {:extension=>".webp", :description=>"WEBP image", :mime_type=>"image/webp"},
 "font/woff"=>
  {:extension=>".woff",
   :description=>"Web Open Font Format (WOFF)",
   :mime_type=>"font/woff"},
 "font/woff2"=>
  {:extension=>".woff2",
   :description=>"Web Open Font Format (WOFF)",
   :mime_type=>"font/woff2"},
 "application/xhtml+xml"=>
  {:extension=>".xhtml",
   :description=>"XHTML",
   :mime_type=>"application/xhtml+xml"},
 "application/xml"=>
  {:extension=>".xml", :description=>"XML", :mime_type=>"application/xml"},
 "application/vnd.mozilla.xul+xml"=>
  {:extension=>".xul",
   :description=>"XUL",
   :mime_type=>"application/vnd.mozilla.xul+xml"},
 "application/zip"=>
  {:extension=>".zip",
   :description=>"ZIP archive",
   :mime_type=>"application/zip"},
 "video/3gpp"=>
  {:extension=>".3gp",
   :description=>"3GPP audio/video container",
   :mime_type=>"video/3gpp"},
 "video/3gpp2"=>
  {:extension=>".3g2",
   :description=>"3GPP2 audio/video container",
   :mime_type=>"video/3gpp2"},
 "application/x-7z-compressed"=>
  {:extension=>".7z",
   :description=>"7-zip archive",
   :mime_type=>"application/x-7z-compressed"}}

end
